const ROWS=[
{id:'vowels',label:'母音',cards:[['あ','ア','a'],['い','イ','i'],['う','ウ','u'],['え','エ','e'],['お','オ','o']]},
{id:'k',label:'K 行',cards:[['か','カ','ka'],['き','キ','ki'],['く','ク','ku'],['け','ケ','ke'],['こ','コ','ko']]},
{id:'s',label:'S 行',cards:[['さ','サ','sa'],['し','シ','shi'],['す','ス','su'],['せ','セ','se'],['そ','ソ','so']]},
{id:'t',label:'T 行',cards:[['た','タ','ta'],['ち','チ','chi'],['つ','ツ','tsu'],['て','テ','te'],['と','ト','to']]},
{id:'n',label:'N 行',cards:[['な','ナ','na'],['に','ニ','ni'],['ぬ','ヌ','nu'],['ね','ネ','ne'],['の','ノ','no']]},
{id:'h',label:'H 行',cards:[['は','ハ','ha'],['ひ','ヒ','hi'],['ふ','フ','fu'],['へ','ヘ','he'],['ほ','ホ','ho']]},
{id:'m',label:'M 行',cards:[['ま','マ','ma'],['み','ミ','mi'],['む','ム','mu'],['め','メ','me'],['も','モ','mo']]},
{id:'y',label:'Y 行',cards:[['や','ヤ','ya'],['ゆ','ユ','yu'],['よ','ヨ','yo']]},
{id:'r',label:'R 行',cards:[['ら','ラ','ra'],['り','リ','ri'],['る','ル','ru'],['れ','レ','re'],['ろ','ロ','ro']]},
{id:'w',label:'W／N',cards:[['わ','ワ','wa'],['を','ヲ','wo / o'],['ん','ン','n']]},
{id:'g',label:'G 行（濁音）',cards:[['が','ガ','ga'],['ぎ','ギ','gi'],['ぐ','グ','gu'],['げ','ゲ','ge'],['ご','ゴ','go']]},
{id:'z',label:'Z 行（濁音）',cards:[['ざ','ザ','za'],['じ','ジ','ji'],['ず','ズ','zu'],['ぜ','ゼ','ze'],['ぞ','ゾ','zo']]},
{id:'d',label:'D 行（濁音）',cards:[['だ','ダ','da'],['ぢ','ヂ','ji'],['づ','ヅ','zu'],['で','デ','de'],['ど','ド','do']]},
{id:'b',label:'B 行（濁音）',cards:[['ば','バ','ba'],['び','ビ','bi'],['ぶ','ブ','bu'],['べ','ベ','be'],['ぼ','ボ','bo']]},
{id:'p',label:'P 行（半濁音）',cards:[['ぱ','パ','pa'],['ぴ','ピ','pi'],['ぷ','プ','pu'],['ぺ','ペ','pe'],['ぽ','ポ','po']]}
];
const $=s=>document.querySelector(s),PREFIX='kana-trainer:v2:';
let userId=localStorage.getItem('kana-trainer:last-user')||'',state=null,queue=[],current=null,revealed=false,completed=0,sessionTotal=0,studyMode='daily';
const defaultState=()=>({version:2,script:'hiragana',selectedRows:['vowels'],newLimit:10,reviewLimit:50,cards:{},history:{},createdAt:Date.now()});
const storageKey=()=>PREFIX+userId.toLowerCase();
function migrate(s){if(!s)return defaultState();return{...defaultState(),...s,version:2,history:s.history||{},cards:s.cards||{}}}
function load(){try{return migrate(JSON.parse(localStorage.getItem(storageKey())))}catch{return defaultState()}}
function save(){localStorage.setItem(storageKey(),JSON.stringify(state));localStorage.setItem('kana-trainer:last-user',userId)}
function dayKey(ts=Date.now()){const d=new Date(ts);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function allCards(){return ROWS.filter(r=>state.selectedRows.includes(r.id)).flatMap(r=>r.cards.map((c,i)=>({id:`${r.id}-${i}`,h:c[0],k:c[1],r:c[2]})))}
function cardState(id){return state.cards[id]||{reps:0,ease:2.5,interval:0,due:0,lapses:0,last:0,correct:0,seen:0}}
function formatInterval(days){if(days<1/1440)return '< 1 分';if(days<1)return `${Math.max(1,Math.round(days*24))} 小時`;if(days<30)return `${Math.round(days)} 天`;return `${Math.round(days/30)} 月`}
function weakness(cs){if(!cs.seen)return 1;const accuracy=cs.correct/cs.seen;return 1+cs.lapses*4+(1-accuracy)*6+(2.5-Math.min(cs.ease,2.5))*2+1/Math.max(1,cs.interval)}
function isWeak(cs){return cs.seen>=2&&(cs.lapses>0||cs.ease<2.3||(cs.correct/cs.seen)<.8)}
function simulate(cs,quality){let next={...cs};if(quality<3){next.reps=0;next.interval=1/1440;next.ease=Math.max(1.3,next.ease-.2);return next}next.reps++;if(next.reps===1)next.interval=1;else if(next.reps===2)next.interval=6;else next.interval=Math.max(1,Math.round(next.interval*next.ease));if(quality===3)next.interval=Math.max(1,Math.round(next.interval*.6));if(quality===5)next.interval=Math.max(4,Math.round(next.interval*1.3));next.ease=Math.max(1.3,next.ease+(0.1-(5-quality)*(0.08+(5-quality)*0.02)));return next}
function sm2Preview(cs){return{hard:simulate(cs,3).interval,good:simulate(cs,4).interval,easy:simulate(cs,5).interval}}
function recordToday(rating){const key=dayKey(),h=state.history[key]||{reviews:0,correct:0,new:0,minutes:0};h.reviews++;if(rating!=='again')h.correct++;if(cardState(current.id).seen===0)h.new++;h.minutes=Math.max(1,Math.round(h.reviews*.18));state.history[key]=h}
function streak(){const keys=Object.keys(state.history).filter(k=>state.history[k].reviews>0).sort().reverse();if(!keys.length)return 0;let d=new Date();const today=dayKey(d),yesterday=dayKey(d.setDate(d.getDate()-1));if(keys[0]!==today&&keys[0]!==yesterday)return 0;let count=0,cursor=new Date(`${keys[0]}T12:00:00`);while(state.history[dayKey(cursor)]?.reviews>0){count++;cursor.setDate(cursor.getDate()-1)}return count}
function updateStats(){const cards=allCards(),now=Date.now(),today=state.history[dayKey()]||{reviews:0,correct:0};const learned=cards.filter(c=>cardState(c.id).reps>0).length,due=cards.filter(c=>{const s=cardState(c.id);return s.reps>0&&s.due<=now}).length,weak=cards.filter(c=>isWeak(cardState(c.id))).length;$('#dueCount').textContent=due;$('#learnedCount').textContent=learned;$('#todayCount').textContent=today.reviews;$('#streakCount').textContent=streak();$('#weakCount').textContent=weak;$('#accuracyCount').textContent=today.reviews?`${Math.round(today.correct/today.reviews*100)}%`:'—';$('#dailyProgress').style.width=`${Math.min(100,today.reviews/Math.max(1,state.newLimit+Math.min(state.reviewLimit,20))*100)}%`;$('#dailyProgressLabel').textContent=`今日完成 ${today.reviews} 次複習`}
function weightedPracticeCards(){let cards=allCards();if(studyMode==='weak'){const weak=cards.filter(c=>isWeak(cardState(c.id)));if(weak.length)cards=weak}const bag=[];cards.forEach(c=>{const w=Math.max(1,Math.min(8,Math.ceil(weakness(cardState(c.id)))));for(let i=0;i<w;i++)bag.push(c)});for(let i=bag.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[bag[i],bag[j]]=[bag[j],bag[i]]}return bag.slice(0,Math.max(20,cards.length*3))}
function buildQueue(){const now=Date.now(),cards=allCards();if(studyMode==='infinite'||studyMode==='weak'){queue=weightedPracticeCards();sessionTotal=0}else{const due=cards.filter(c=>{const s=cardState(c.id);return s.reps>0&&s.due<=now}).sort((a,b)=>weakness(cardState(b.id))-weakness(cardState(a.id))||cardState(a.id).due-cardState(b.id).due).slice(0,state.reviewLimit);const fresh=cards.filter(c=>cardState(c.id).seen===0).sort(()=>Math.random()-.5).slice(0,state.newLimit);queue=[...due,...fresh];sessionTotal=queue.length}completed=0;updateStats();nextCard()}
function renderPrompt(c){if(state.script==='hiragana')return c.h;if(state.script==='katakana')return c.k;return Math.random()<.5?c.h:c.k}
function nextCard(){revealed=false;current=queue.shift()||null;$('#ratingButtons').hidden=true;$('#cardAnswer').hidden=true;$('#cardHint').hidden=false;$('#completeActions').hidden=true;const hasCards=allCards().length>0;$('#emptyState').hidden=hasCards;$('#studyPanel').hidden=!hasCards;if(!hasCards)return;if(!current&&(studyMode==='infinite'||studyMode==='weak')){queue=weightedPracticeCards();current=queue.shift()||null}if(!current){$('#cardPrompt').textContent='完成！';$('#cardHint').textContent='今天的卡片都複習完了';$('#queueLabel').textContent='做得很好';$('#progressBar').style.width='100%';$('#completeActions').hidden=false;return}$('#cardPrompt').textContent=renderPrompt(current);$('#cardHint').textContent='點一下顯示答案';$('#queueLabel').textContent=studyMode==='daily'?`剩下 ${queue.length+1} 張`:`已練 ${completed} 張 · ${studyMode==='weak'?'弱點':'無限'}模式`;$('#progressBar').style.width=studyMode==='daily'&&sessionTotal?`${completed/sessionTotal*100}%`:'100%';const ints=sm2Preview(cardState(current.id));$('#hardInterval').textContent=formatInterval(ints.hard);$('#goodInterval').textContent=formatInterval(ints.good);$('#easyInterval').textContent=formatInterval(ints.easy)}
function reveal(){if(!current||revealed)return;revealed=true;const cs=cardState(current.id);$('#cardAnswer').innerHTML=`<strong>${current.r}</strong><small>${cs.seen?`正確率 ${Math.round(cs.correct/cs.seen*100)}% · 忘記 ${cs.lapses} 次`:'新卡'}</small>`;$('#cardAnswer').hidden=false;$('#cardHint').hidden=true;$('#ratingButtons').hidden=false}
function rate(rating){if(!current)return;const now=Date.now(),cs=cardState(current.id),quality={again:1,hard:3,good:4,easy:5}[rating];recordToday(rating);cs.seen=(cs.seen||0)+1;if(quality>=3)cs.correct=(cs.correct||0)+1;else cs.lapses=(cs.lapses||0)+1;Object.assign(cs,simulate(cs,quality));cs.last=now;cs.due=now+cs.interval*86400000;state.cards[current.id]=cs;if(rating==='again')queue.splice(Math.min(3,queue.length),0,current);save();completed++;updateStats();nextCard()}
function setStudyMode(mode){studyMode=mode;document.querySelectorAll('.practice-mode').forEach(b=>b.classList.remove('active'));$(`#${mode==='daily'?'dailyModeBtn':mode==='infinite'?'infiniteModeBtn':'weakModeBtn'}`).classList.add('active');buildQueue()}
function renderSettings(){$('#rowSelector').innerHTML=ROWS.map(r=>`<label class="row-chip"><input type="checkbox" value="${r.id}" ${state.selectedRows.includes(r.id)?'checked':''}><span>${r.label}<br><small>${r.cards.map(c=>c[0]).join(' ')}</small></span></label>`).join('');$('#newLimitInput').value=state.newLimit;$('#reviewLimitInput').value=state.reviewLimit}
function setScript(script){state.script=script;save();document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.script===script));buildQueue()}
function enter(id){userId=id.trim();if(!userId)return;state=load();$('#loginView').hidden=true;$('#appView').hidden=false;$('#currentUser').textContent=userId;renderSettings();setScript(state.script)}
function switchUser(){save();userId='';state=null;localStorage.removeItem('kana-trainer:last-user');$('#appView').hidden=true;$('#loginView').hidden=false;$('#userIdInput').value='';$('#settingsDialog').close()}
$('#loginBtn').onclick=()=>enter($('#userIdInput').value);$('#userIdInput').addEventListener('keydown',e=>{if(e.key==='Enter')enter(e.target.value)});$('#card').onclick=reveal;document.querySelectorAll('[data-rating]').forEach(b=>b.onclick=()=>rate(b.dataset.rating));document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>setScript(b.dataset.script));$('#dailyModeBtn').onclick=()=>setStudyMode('daily');$('#infiniteModeBtn').onclick=()=>setStudyMode('infinite');$('#weakModeBtn').onclick=()=>setStudyMode('weak');$('#continuePracticeBtn').onclick=()=>setStudyMode('infinite');$('#restartDailyBtn').onclick=()=>{queue=allCards().sort(()=>Math.random()-.5);sessionTotal=queue.length;completed=0;nextCard()};function openSettings(){renderSettings();$('#settingsDialog').showModal()}$('#settingsBtn').onclick=openSettings;$('#emptySettingsBtn').onclick=openSettings;
$('#saveSettingsBtn').onclick=e=>{e.preventDefault();state.selectedRows=[...document.querySelectorAll('#rowSelector input:checked')].map(i=>i.value);state.newLimit=Math.max(1,Math.min(50,+$('#newLimitInput').value||10));state.reviewLimit=Math.max(5,Math.min(200,+$('#reviewLimitInput').value||50));save();$('#settingsDialog').close();buildQueue()};
$('#switchUserBtn').onclick=switchUser;$('#resetBtn').onclick=()=>{if(confirm(`確定要清除 ${userId} 的所有學習進度嗎？`)){state=defaultState();save();renderSettings();buildQueue()}};
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify({version:2,userId,state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`kana-${userId}-${dayKey()}.json`;a.click();URL.revokeObjectURL(a.href)};
$('#importInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());if(!data.state||!Array.isArray(data.state.selectedRows))throw new Error();state=migrate(data.state);save();renderSettings();buildQueue();alert('匯入完成')}catch{alert('備份檔格式不正確')}finally{e.target.value=''}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');if(userId){$('#userIdInput').value=userId;enter(userId)}