const coachDialog=document.createElement('dialog');coachDialog.id='coachDialog';coachDialog.innerHTML=`<section class="coach-shell"><header><div><p class="eyebrow">Personal learning coach</p><h2>今日教練</h2></div><button id="coachClose" class="ghost">關閉</button></header><div id="coachHero" class="coach-hero"></div><div id="coachFocus" class="coach-focus"></div><div id="coachPlan" class="coach-plan"></div><button id="coachPractice" class="primary full">開始建議練習</button></section>`;document.body.appendChild(coachDialog);
const coachMistakeKey=()=>`kana-master:mistakes:${(userId||'guest').toLowerCase()}`;
function coachMistakes(){try{return JSON.parse(localStorage.getItem(coachMistakeKey()))||{items:{}}}catch{return{items:{}}}}
function coachCardMap(){return new Map((window.KanaQuiz?.getAllCards?.()||[]).map(card=>[card.id,card]))}
function coachSignals(){const map=coachCardMap(),book=coachMistakes();return [...map.values()].map(card=>{const sm=state?.cards?.[card.id]||{},mistake=book.items?.[card.id]||{};const unresolved=Math.max(0,(mistake.wrong||0)-(mistake.correct||0));const seen=sm.seen||0,accuracy=seen?(sm.correct||0)/seen:1;const score=unresolved*8+(sm.lapses||0)*5+(1-accuracy)*5+(sm.ease&&sm.ease<2.3?(2.3-sm.ease)*4:0);return{card,score,unresolved,lapses:sm.lapses||0,accuracy,seen,lastSelected:mistake.lastSelected||''}}).sort((a,b)=>b.score-a.score)}
function coachReport(){const signals=coachSignals(),focus=signals.filter(x=>x.score>0).slice(0,3),today=state?.history?.[dayKey()]||{reviews:0,correct:0};const accuracy=today.reviews?Math.round(today.correct/today.reviews*100):null;let headline='今天先建立穩定節奏';let summary='目前資料還不多，先完成一輪今日學習，教練就能開始找出你的弱點。';if(focus.length){headline=`最需要注意：${focus[0].card.hiragana}／${focus[0].card.katakana}`;summary=focus[0].unresolved?`你仍有 ${focus[0].unresolved} 次尚未克服的混淆，建議先做短次數、高專注的辨識練習。`:`這張卡在間隔複習中較不穩定，今天再加強幾次即可。`}else if(today.reviews>=5){headline='今天表現很穩定';summary=`已完成 ${today.reviews} 次複習${accuracy!==null?`，正確率 ${accuracy}%`:''}。維持現在的節奏，不需要過度練習。`}return{signals,focus,today,accuracy,headline,summary}}
function focusReason(item){const reasons=[];if(item.unresolved)reasons.push(`錯題差額 ${item.unresolved}`);if(item.lapses)reasons.push(`忘記 ${item.lapses} 次`);if(item.seen&&item.accuracy<.8)reasons.push(`正確率 ${Math.round(item.accuracy*100)}%`);if(item.lastSelected)reasons.push(`曾選成 ${item.lastSelected}`);return reasons.join(' · ')||'近期需要再確認'}
function renderCoach(){const report=coachReport();document.querySelector('#coachHero').innerHTML=`<span>給 ${(userId||'你')} 的建議</span><strong>${report.headline}</strong><p>${report.summary}</p>`;document.querySelector('#coachFocus').innerHTML=report.focus.length?`<h3>優先複習</h3>${report.focus.map((item,index)=>`<article><b>${index+1}</b><div class="coach-kana"><strong>${item.card.hiragana}</strong><strong>${item.card.katakana}</strong></div><div><h4>${item.card.romaji}</h4><p>${focusReason(item)}</p></div></article>`).join('')}`:'<div class="coach-clear"><strong>目前沒有明顯弱點 🎉</strong><p>完成今天的卡片即可，不必額外加量。</p></div>';const count=report.focus.length?Math.min(10,Math.max(4,report.focus.length*3)):5;document.querySelector('#coachPlan').innerHTML=`<h3>今日計畫</h3><ol><li>先完成到期的 SM-2 卡片</li><li>${report.focus.length?`針對上方假名做 ${count} 題選擇題`:'做 5 題選擇題建立辨識資料'}</li><li>答錯時先看外型聯想，再比較易混淆字</li></ol>`;document.querySelector('#coachPractice').textContent=report.focus.length?`練習這 ${report.focus.length} 個弱點`:'開始 5 題暖身';document.querySelector('#coachPractice').dataset.ids=report.focus.map(x=>x.card.id).join(',')}
function openCoach(){renderCoach();coachDialog.showModal()}
document.querySelector('#coachClose').onclick=()=>coachDialog.close();document.querySelector('#coachPractice').onclick=e=>{const ids=new Set(e.currentTarget.dataset.ids.split(',').filter(Boolean)),all=window.KanaQuiz?.getAllCards?.()||[],cards=ids.size?all.filter(card=>ids.has(card.id)):all;coachDialog.close();window.KanaQuiz?.open(cards)};
(function installCoach(){const modes=document.querySelector('.practice-tabs'),anchor=document.querySelector('#mistakeBookBtn')||document.querySelector('#quizModeBtn');if(modes&&anchor&&!document.querySelector('#coachBtn')){const button=document.createElement('button');button.id='coachBtn';button.className='practice-mode coach-button';button.textContent='今日教練';anchor.after(button);button.onclick=openCoach}const link=document.createElement('link');link.rel='stylesheet';link.href='coach.css';document.head.appendChild(link)})();