const CURRICULUM={basic:{label:'第一階段｜清音',description:'46 個基礎假名',rows:['vowels','k','s','t','n','h','m','y','r','w']},voiced:{label:'第二階段｜濁音・半濁音',description:'在清音上加入濁點與半濁點',rows:['g','z','d','b','p']},yoon:{label:'第三階段｜拗音',description:'小ゃ・ゅ・ょ組合音',rows:['yoon']}};
const YOON_CARDS=[['きゃ','キャ','kya'],['きゅ','キュ','kyu'],['きょ','キョ','kyo'],['しゃ','シャ','sha'],['しゅ','シュ','shu'],['しょ','ショ','sho'],['ちゃ','チャ','cha'],['ちゅ','チュ','chu'],['ちょ','チョ','cho'],['にゃ','ニャ','nya'],['にゅ','ニュ','nyu'],['にょ','ニョ','nyo'],['ひゃ','ヒャ','hya'],['ひゅ','ヒュ','hyu'],['ひょ','ヒョ','hyo'],['みゃ','ミャ','mya'],['みゅ','ミュ','myu'],['みょ','ミョ','myo'],['りゃ','リャ','rya'],['りゅ','リュ','ryu'],['りょ','リョ','ryo'],['ぎゃ','ギャ','gya'],['ぎゅ','ギュ','gyu'],['ぎょ','ギョ','gyo'],['じゃ','ジャ','ja'],['じゅ','ジュ','ju'],['じょ','ジョ','jo'],['びゃ','ビャ','bya'],['びゅ','ビュ','byu'],['びょ','ビョ','byo'],['ぴゃ','ピャ','pya'],['ぴゅ','ピュ','pyu'],['ぴょ','ピョ','pyo']];
if(!ROWS.some(row=>row.id==='yoon'))ROWS.push({id:'yoon',label:'拗音（小ゃゅょ）',cards:YOON_CARDS});
function curriculumStage(){const selected=new Set(state?.selectedRows||[]);if(CURRICULUM.yoon.rows.some(id=>selected.has(id)))return 3;if(CURRICULUM.voiced.rows.some(id=>selected.has(id)))return 2;return 1}
function applyCurriculum(ids){document.querySelectorAll('#rowSelector input').forEach(input=>{input.checked=ids.includes(input.value)});updateCurriculumPreview()}
function cumulativeRows(stage){return [...CURRICULUM.basic.rows,...(stage>=2?CURRICULUM.voiced.rows:[]),...(stage>=3?CURRICULUM.yoon.rows:[])]}
function updateCurriculumPreview(){const checked=[...document.querySelectorAll('#rowSelector input:checked')].map(input=>input.value);const count=ROWS.filter(row=>checked.includes(row.id)).reduce((sum,row)=>sum+row.cards.length,0);const preview=document.querySelector('#curriculumPreview');if(preview)preview.textContent=`目前選擇 ${checked.length} 列，共 ${count} 張卡`}
function decorateCurriculum(){const selector=document.querySelector('#rowSelector');if(!selector)return;selector.querySelectorAll('.row-chip').forEach(label=>{const id=label.querySelector('input')?.value;const level=CURRICULUM.basic.rows.includes(id)?1:CURRICULUM.voiced.rows.includes(id)?2:3;label.dataset.level=level});updateCurriculumPreview()}
(function installCurriculum(){const selector=document.querySelector('#rowSelector');const section=selector?.closest('section');if(section&&!document.querySelector('#curriculumPicker')){const picker=document.createElement('div');picker.id='curriculumPicker';picker.className='curriculum-picker';picker.innerHTML=`<div class="curriculum-heading"><div><p class="eyebrow">Recommended path</p><h3>選擇學習階段</h3></div><span id="curriculumPreview"></span></div><div class="curriculum-levels">${[1,2,3].map(level=>{const item=level===1?CURRICULUM.basic:level===2?CURRICULUM.voiced:CURRICULUM.yoon;return `<button type="button" class="curriculum-level" data-stage="${level}"><b>${level}</b><span><strong>${item.label}</strong><small>${item.description}</small></span></button>`}).join('')}</div><p class="curriculum-hint">選擇階段會累積前面的內容；下方仍可逐列微調。</p>`;section.insertBefore(picker,selector);picker.querySelectorAll('[data-stage]').forEach(button=>button.onclick=()=>applyCurriculum(cumulativeRows(+button.dataset.stage)));selector.addEventListener('change',updateCurriculumPreview)}
const observer=new MutationObserver(decorateCurriculum);if(selector)observer.observe(selector,{childList:true});decorateCurriculum();
const dashboard=document.querySelector('.dashboard');if(dashboard&&!document.querySelector('#curriculumBadge')){const badge=document.createElement('div');badge.id='curriculumBadge';badge.className='curriculum-badge';dashboard.appendChild(badge)}
const originalUpdateStats=updateStats;updateStats=function(){originalUpdateStats();const stage=curriculumStage(),badge=document.querySelector('#curriculumBadge');if(badge)badge.innerHTML=`<span>目前課程</span><strong>Stage ${stage} · ${stage===1?'清音':stage===2?'濁音／半濁音':'拗音'}</strong>`};
if(state){renderSettings();buildQueue()}})();