let listeningCards=[],listeningCurrent=null,listeningCorrect='',listeningScore=0,listeningCount=0;
const listeningDialog=document.createElement('dialog');listeningDialog.id='listeningDialog';listeningDialog.innerHTML=`<section class="listening-shell"><header><div><p class="eyebrow">Listening practice</p><h2>聽音辨識</h2></div><button id="listeningClose" class="ghost">關閉</button></header><p id="listeningProgress" class="listening-progress"></p><div class="listening-prompt"><button id="listeningSpeak" class="listening-speaker" aria-label="播放發音">🔊</button><p>聽發音，選出正確假名</p></div><div id="listeningOptions" class="listening-options"></div><div id="listeningFeedback" class="listening-feedback" hidden></div><button id="listeningNext" class="primary full" hidden>下一題</button><p class="listening-note">發音使用裝置內建的日文語音；不同裝置的聲音可能略有差異。</p></section>`;document.body.appendChild(listeningDialog);
function listeningShuffle(items){return [...items].sort(()=>Math.random()-.5)}
function listeningSelectedCards(){const selected=new Set(state?.selectedRows||[]);return (window.KanaQuiz?.getAllCards?.()||[]).filter(card=>selected.has(card.rowId))}
function listeningDisplay(card){if(state?.script==='katakana')return card.katakana;if(state?.script==='mixed')return Math.random()<.5?card.hiragana:card.katakana;return card.hiragana}
function speakKana(card=listeningCurrent){if(!card||!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(card.hiragana);utterance.lang='ja-JP';utterance.rate=.72;utterance.pitch=1;const voice=window.speechSynthesis.getVoices().find(v=>v.lang?.toLowerCase().startsWith('ja'));if(voice)utterance.voice=voice;window.speechSynthesis.speak(utterance)}
function nextListening(){if(!listeningCards.length)return;listeningCount++;listeningCurrent=listeningCards[Math.floor(Math.random()*listeningCards.length)];listeningCorrect=listeningDisplay(listeningCurrent);const confusable=(listeningCurrent.confusableKana||[]).map(k=>(window.KanaQuiz?.getAllCards?.()||[]).find(c=>c.hiragana===k||c.katakana===k)).filter(Boolean).map(listeningDisplay);const pool=(window.KanaQuiz?.getAllCards?.()||[]).map(listeningDisplay).filter(k=>k!==listeningCorrect&&!confusable.includes(k));const options=listeningShuffle([listeningCorrect,...confusable.slice(0,2),...listeningShuffle(pool).slice(0,Math.max(0,3-confusable.length))]).slice(0,4);document.querySelector('#listeningProgress').textContent=`第 ${listeningCount} 題 · 答對 ${listeningScore} 題`;document.querySelector('#listeningFeedback').hidden=true;document.querySelector('#listeningNext').hidden=true;document.querySelector('#listeningOptions').innerHTML=options.map(k=>`<button class="listening-option" data-kana="${k}">${k}</button>`).join('');document.querySelectorAll('.listening-option').forEach(button=>button.onclick=()=>answerListening(button));setTimeout(()=>speakKana(),160)}
function answerListening(button){document.querySelectorAll('.listening-option').forEach(option=>{option.disabled=true;if(option.dataset.kana===listeningCorrect)option.classList.add('correct')});const selected=button.dataset.kana,ok=selected===listeningCorrect;if(ok){listeningScore++;button.classList.add('correct')}else button.classList.add('wrong');const feedback=document.querySelector('#listeningFeedback');feedback.innerHTML=`<strong>${ok?'聽對了！':'再聽一次'}</strong><p>正確答案：${listeningCurrent.hiragana}／${listeningCurrent.katakana}（${listeningCurrent.romaji}）</p><p>${listeningCurrent.shapeMnemonic?.hiragana||''}</p>`;feedback.hidden=false;document.querySelector('#listeningNext').hidden=false;window.dispatchEvent(new CustomEvent('kana-quiz-answer',{detail:{ok,selected,correct:listeningCorrect,card:listeningCurrent,script:'listening',answeredAt:Date.now()}}));speakKana()}
function openListening(){listeningCards=listeningSelectedCards();if(!listeningCards.length)return;listeningScore=0;listeningCount=0;listeningDialog.showModal();nextListening()}
document.querySelector('#listeningSpeak').onclick=()=>speakKana();document.querySelector('#listeningNext').onclick=nextListening;document.querySelector('#listeningClose').onclick=()=>{window.speechSynthesis?.cancel();listeningDialog.close()};
(function installListening(){const tabs=document.querySelector('.practice-tabs'),anchor=document.querySelector('#quizModeBtn');if(tabs&&anchor&&!document.querySelector('#listeningModeBtn')){const button=document.createElement('button');button.id='listeningModeBtn';button.className='practice-mode';button.textContent='聽音';anchor.after(button);button.onclick=openListening}})();