const mistakeDialog=document.createElement('dialog');mistakeDialog.id='mistakeDialog';mistakeDialog.innerHTML=`<section class="mistake-shell"><header><div><p class="eyebrow">Personal review</p><h2>錯題本</h2></div><button id="mistakeClose" class="ghost">關閉</button></header><div id="mistakeSummary" class="mistake-summary"></div><div id="mistakeList" class="mistake-list"></div><div class="mistake-actions"><button id="practiceMistakes" class="primary">練習錯題</button><button id="clearMistakes" class="ghost">清除錯題</button></div></section>`;document.body.appendChild(mistakeDialog);
const mistakeKey=()=>`kana-master:mistakes:${(userId||'guest').toLowerCase()}`;
function loadMistakes(){try{return JSON.parse(localStorage.getItem(mistakeKey()))||{items:{},total:0,corrected:0}}catch{return{items:{},total:0,corrected:0}}}
function saveMistakes(book){localStorage.setItem(mistakeKey(),JSON.stringify(book))}
function recordMistake(detail){const book=loadMistakes(),id=detail.card.id,item=book.items[id]||{id,hiragana:detail.card.hiragana,katakana:detail.card.katakana,romaji:detail.card.romaji,wrong:0,correct:0,lastSelected:'',lastAt:0};if(detail.ok){item.correct++;book.corrected++}else{item.wrong++;item.lastSelected=detail.selected;book.total++}item.lastAt=detail.answeredAt;book.items[id]=item;saveMistakes(book)}
function mistakeCards(){const book=loadMistakes();return Object.values(book.items).filter(i=>i.wrong>i.correct).sort((a,b)=>(b.wrong-b.correct)-(a.wrong-a.correct)||b.lastAt-a.lastAt)}
function renderMistakes(){const book=loadMistakes(),items=mistakeCards();document.querySelector('#mistakeSummary').innerHTML=`<div><strong>${items.length}</strong><span>待加強假名</span></div><div><strong>${book.total}</strong><span>累計答錯</span></div><div><strong>${book.corrected}</strong><span>後來答對</span></div>`;document.querySelector('#mistakeList').innerHTML=items.length?items.map(i=>`<article class="mistake-item"><div class="mistake-kana"><strong>${i.hiragana}</strong><strong>${i.katakana}</strong></div><div><b>${i.romaji}</b><span>答錯 ${i.wrong} 次 · 答對 ${i.correct} 次</span>${i.lastSelected?`<small>上次選成：${i.lastSelected}</small>`:''}</div></article>`).join(''):'<div class="mistake-empty"><strong>目前沒有待加強的假名 🎉</strong><p>去做幾題選擇題，錯誤會自動收進這裡。</p></div>';document.querySelector('#practiceMistakes').disabled=!items.length}
function openMistakes(){renderMistakes();mistakeDialog.showModal()}
window.addEventListener('kana-quiz-answer',e=>recordMistake(e.detail));
document.querySelector('#mistakeClose').onclick=()=>mistakeDialog.close();document.querySelector('#mistakeBookBtn').onclick=openMistakes;
document.querySelector('#clearMistakes').onclick=()=>{if(confirm('確定要清除目前學習者的錯題紀錄嗎？')){localStorage.removeItem(mistakeKey());renderMistakes()}};
document.querySelector('#practiceMistakes').onclick=()=>{const ids=new Set(mistakeCards().map(i=>i.id)),cards=window.KanaQuiz?.getCards().filter(c=>ids.has(c.id))||[];if(cards.length){mistakeDialog.close();window.KanaQuiz.open(cards)}};