const progressMapDialog=document.createElement('dialog');progressMapDialog.id='progressMapDialog';progressMapDialog.innerHTML=`<section class="progress-map-shell"><header><div><p class="eyebrow">Mastery overview</p><h2>學習進度地圖</h2></div><button id="progressMapClose" class="ghost">關閉</button></header><div id="masterySummary" class="mastery-summary"></div><div class="mastery-legend"><span class="new"><i></i>未學</span><span class="learning"><i></i>學習中</span><span class="mastered"><i></i>已掌握</span><span class="weak"><i></i>弱點</span></div><div id="progressMapRows" class="progress-map-rows"></div><div class="progress-map-actions"><button id="progressWeakPractice" class="primary">練習所有弱點</button><button id="progressMapSettings" class="ghost">調整學習範圍</button></div></section>`;document.body.appendChild(progressMapDialog);
function masteryState(id){const cs=cardState(id);if(!cs.seen)return'new';const accuracy=cs.seen?cs.correct/cs.seen:0;if(cs.lapses>0||cs.ease<2.3||accuracy<.8)return'weak';if(cs.reps>=3&&cs.interval>=7&&accuracy>=.85)return'mastered';return'learning'}
function masteryLabel(status){return{new:'未學',learning:'學習中',mastered:'已掌握',weak:'弱點'}[status]}
function progressRows(){const selected=new Set(state?.selectedRows||[]);return ROWS.map(row=>({...row,selected:selected.has(row.id)}))}
function progressCards(){return progressRows().flatMap(row=>row.cards.map((card,index)=>({id:`${row.id}-${index}`,rowId:row.id,h:card[0],k:card[1],r:card[2],selected:row.selected,status:masteryState(`${row.id}-${index}`)})))}
function renderProgressMap(){const cards=progressCards(),selected=cards.filter(card=>card.selected),counts={new:0,learning:0,mastered:0,weak:0};selected.forEach(card=>counts[card.status]++);document.querySelector('#masterySummary').innerHTML=`<div><strong>${counts.new}</strong><span>未學</span></div><div><strong>${counts.learning}</strong><span>學習中</span></div><div><strong>${counts.mastered}</strong><span>已掌握</span></div><div><strong>${counts.weak}</strong><span>弱點</span></div>`;document.querySelector('#progressMapRows').innerHTML=progressRows().map(row=>{const rowCards=cards.filter(card=>card.rowId===row.id),learned=rowCards.filter(card=>card.status!=='new').length;return `<section class="progress-map-row"><header><h3>${row.label}</h3><small>${row.selected?`${learned}/${rowCards.length} 已開始`:'尚未加入課程'}</small></header><div class="kana-grid">${rowCards.map(card=>`<button class="kana-cell ${card.status}" data-card-id="${card.id}" title="${card.r} · ${masteryLabel(card.status)}" ${row.selected?'':'disabled'}><strong>${state?.script==='katakana'?card.k:card.h}</strong><small>${card.r}</small></button>`).join('')}</div></section>`}).join('');document.querySelectorAll('.kana-cell:not([disabled])').forEach(button=>button.onclick=()=>practiceProgressCards([button.dataset.cardId]));document.querySelector('#progressWeakPractice').disabled=!counts.weak}
function practiceProgressCards(ids){const wanted=new Set(ids),cards=(window.KanaQuiz?.getAllCards?.()||[]).filter(card=>wanted.has(card.id));if(cards.length){progressMapDialog.close();window.KanaQuiz.open(cards)}}
function openProgressMap(){renderProgressMap();progressMapDialog.showModal()}
document.querySelector('#progressMapClose').onclick=()=>progressMapDialog.close();document.querySelector('#progressWeakPractice').onclick=()=>practiceProgressCards(progressCards().filter(card=>card.selected&&card.status==='weak').map(card=>card.id));document.querySelector('#progressMapSettings').onclick=()=>{progressMapDialog.close();renderSettings();document.querySelector('#settingsDialog').showModal()};
(function installProgressMap(){const modes=document.querySelector('.practice-tabs'),anchor=document.querySelector('#coachBtn')||document.querySelector('#mistakeBookBtn')||document.querySelector('#quizModeBtn');if(modes&&anchor&&!document.querySelector('#progressMapBtn')){const button=document.createElement('button');button.id='progressMapBtn';button.className='practice-mode';button.textContent='進度地圖';anchor.after(button);button.onclick=openProgressMap}})();