let quizAllCards=[],quizSessionCards=[],quizCurrent=null,quizScore=0,quizCount=0;
const quizDialog=document.createElement('dialog');quizDialog.id='quizDialog';quizDialog.innerHTML=`<section class="quiz-shell"><header><div><p class="eyebrow">Adaptive practice</p><h2>易混淆選擇題</h2></div><button id="quizClose" class="ghost">關閉</button></header><p id="quizProgress" class="quiz-progress"></p><div class="quiz-question"><span>請選出</span><strong id="quizRomaji"></strong></div><div id="quizOptions" class="quiz-options"></div><div id="quizFeedback" class="quiz-feedback" hidden></div><button id="quizNext" class="primary full" hidden>下一題</button></section>`;document.body.appendChild(quizDialog);
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function flattenQuizCards(data){return data.rows.flatMap(row=>row.cards.map((card,index)=>({...card,id:`${row.id}-${index}`,rowId:row.id}))) }
function quizScript(card){if(state?.script==='katakana')return card.katakana;if(state?.script==='mixed')return Math.random()<.5?card.hiragana:card.katakana;return card.hiragana}
function findKana(kana){return quizAllCards.find(c=>c.hiragana===kana||c.katakana===kana)}
function nextQuiz(){if(!quizSessionCards.length)return;quizCount++;quizCurrent=quizSessionCards[Math.floor(Math.random()*quizSessionCards.length)];const correct=quizScript(quizCurrent);const confusable=(quizCurrent.confusableKana||[]).map(findKana).filter(Boolean).map(quizScript);const pool=quizAllCards.map(quizScript).filter(k=>k!==correct&&!confusable.includes(k));const options=shuffle([correct,...confusable.slice(0,2),...shuffle(pool).slice(0,Math.max(0,3-confusable.length))]).slice(0,4);document.querySelector('#quizRomaji').textContent=quizCurrent.romaji;document.querySelector('#quizProgress').textContent=`第 ${quizCount} 題 · 答對 ${quizScore} 題`;document.querySelector('#quizFeedback').hidden=true;document.querySelector('#quizNext').hidden=true;document.querySelector('#quizOptions').innerHTML=options.map(k=>`<button class="quiz-option" data-kana="${k}">${k}</button>`).join('');document.querySelectorAll('.quiz-option').forEach(b=>b.onclick=()=>answerQuiz(b,correct))}
function answerQuiz(button,correct){document.querySelectorAll('.quiz-option').forEach(b=>{b.disabled=true;if(b.dataset.kana===correct)b.classList.add('correct')});const selected=button.dataset.kana,ok=selected===correct;if(ok){quizScore++;button.classList.add('correct')}else button.classList.add('wrong');const script=correct===quizCurrent.katakana?'katakana':'hiragana';const shape=quizCurrent.shapeMnemonic?.[script]||'';const conf=(quizCurrent.confusableKana||[]).join('、')||'無';const feedback=document.querySelector('#quizFeedback');feedback.innerHTML=`<strong>${ok?'答對了！':'再注意一下'}</strong><p>正確答案：${correct}（${quizCurrent.romaji}）</p><p>${shape}</p><p>容易混淆：${conf}</p>`;feedback.hidden=false;document.querySelector('#quizNext').hidden=false;window.dispatchEvent(new CustomEvent('kana-quiz-answer',{detail:{ok,selected,correct,card:quizCurrent,script,answeredAt:Date.now()}}))}
function openQuiz(cards=quizAllCards){if(!cards.length)return;quizSessionCards=[...cards];quizScore=0;quizCount=0;quizDialog.showModal();nextQuiz()}
window.KanaQuiz={open:openQuiz,getCards:()=>quizSessionCards,getAllCards:()=>quizAllCards};
document.querySelector('#quizClose').onclick=()=>quizDialog.close();document.querySelector('#quizNext').onclick=nextQuiz;
KANA_DATA_PROMISE.then(data=>{quizAllCards=flattenQuizCards(data);quizSessionCards=[...quizAllCards];const btn=document.querySelector('#quizModeBtn');if(btn)btn.onclick=()=>openQuiz(quizAllCards)});
(function loadExtensions(){const modes=document.querySelector('.practice-tabs'),quizButton=document.querySelector('#quizModeBtn');if(modes&&quizButton&&!document.querySelector('#mistakeBookBtn')){const button=document.createElement('button');button.id='mistakeBookBtn';button.className='practice-mode';button.textContent='錯題本';quizButton.after(button)}[['mistakes.css','stylesheet'],['coach.css','stylesheet']].forEach(([href])=>{const link=document.createElement('link');link.rel='stylesheet';link.href=href;document.head.appendChild(link)});['mistakes.js','coach.js'].forEach(src=>{const script=document.createElement('script');script.src=src;document.body.appendChild(script)})})();