let typingCards=[],typingCurrent=null,typingScore=0,typingCount=0;
const typingAliases={shi:['shi','si'],chi:['chi','ti'],tsu:['tsu','tu'],fu:['fu','hu'],ji:['ji','zi'],zu:['zu','du'],"wo / o":['wo','o']};
const typingDialog=document.createElement('dialog');typingDialog.id='typingDialog';typingDialog.innerHTML=`<form class="typing-shell" onsubmit="return false"><header><div><p class="eyebrow">Active recall</p><h2>羅馬字輸入</h2></div><button id="typingClose" type="button" class="ghost">關閉</button></header><p id="typingProgress" class="typing-progress"></p><div class="typing-question"><span>請輸入這個假名的羅馬字</span><strong id="typingKana"></strong></div><label class="typing-field"><span>Romaji</span><input id="typingInput" autocomplete="off" autocapitalize="none" spellcheck="false" inputmode="latin" placeholder="例如 shi"></label><div id="typingFeedback" class="typing-feedback" hidden></div><div class="typing-actions"><button id="typingSubmit" class="primary" type="submit">確認</button><button id="typingNext" class="ghost" type="button" hidden>下一題</button></div></form>`;document.body.appendChild(typingDialog);
function typingAccepted(card){const raw=String(card.r||card.romaji||'').toLowerCase().trim();return typingAliases[raw]||raw.split('/').map(x=>x.trim())}
function typingDisplay(card){if(state?.script==='katakana')return card.k;if(state?.script==='mixed')return Math.random()<.5?card.h:card.k;return card.h}
function nextTyping(){if(!typingCards.length)return;typingCount++;typingCurrent=typingCards[Math.floor(Math.random()*typingCards.length)];document.querySelector('#typingKana').textContent=typingDisplay(typingCurrent);document.querySelector('#typingProgress').textContent=`第 ${typingCount} 題 · 答對 ${typingScore} 題`;const input=document.querySelector('#typingInput');input.value='';input.disabled=false;document.querySelector('#typingFeedback').hidden=true;document.querySelector('#typingSubmit').hidden=false;document.querySelector('#typingNext').hidden=true;setTimeout(()=>input.focus(),50)}
function answerTyping(){if(!typingCurrent)return;const input=document.querySelector('#typingInput'),value=input.value.toLowerCase().trim(),accepted=typingAccepted(typingCurrent),ok=accepted.includes(value);if(!value)return input.focus();if(ok)typingScore++;input.disabled=true;const correct=String(typingCurrent.r||typingCurrent.romaji);const feedback=document.querySelector('#typingFeedback');feedback.className=`typing-feedback ${ok?'correct':'wrong'}`;feedback.innerHTML=`<strong>${ok?'答對了！':'再想一下'}</strong><p>${typingCurrent.h}／${typingCurrent.k}：${correct}</p>${accepted.length>1?`<small>也接受：${accepted.join('、')}</small>`:''}`;feedback.hidden=false;document.querySelector('#typingSubmit').hidden=true;document.querySelector('#typingNext').hidden=false;window.dispatchEvent(new CustomEvent('kana-quiz-answer',{detail:{ok,selected:value,correct,card:{...KANA_MNEMONICS[typingCurrent.id],id:typingCurrent.id,hiragana:typingCurrent.h,katakana:typingCurrent.k,romaji:correct},script:typingCurrent.h===document.querySelector('#typingKana').textContent?'hiragana':'katakana',answeredAt:Date.now()}}))}
function openTyping(){typingCards=allCards();if(!typingCards.length)return;typingScore=0;typingCount=0;typingDialog.showModal();nextTyping()}
document.querySelector('#typingClose').onclick=()=>typingDialog.close();document.querySelector('#typingNext').onclick=nextTyping;document.querySelector('#typingSubmit').onclick=answerTyping;document.querySelector('#typingInput').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();document.querySelector('#typingNext').hidden?answerTyping():nextTyping()}});
(function installTyping(){const modes=document.querySelector('.practice-tabs'),anchor=document.querySelector('#listeningModeBtn')||document.querySelector('#quizModeBtn');if(modes&&anchor&&!document.querySelector('#typingModeBtn')){const button=document.createElement('button');button.id='typingModeBtn';button.className='practice-mode';button.textContent='羅馬字輸入';anchor.after(button);button.onclick=openTyping}})();